// import  store  from '@store/storeConfig/store';
import axios from "axios";

export const baseAxios = axios.create( {
    baseURL: 'http://192.168.0.18:9091/api/merchandising'
} );


const accessToken = "eyJhbGciOiJSUzI1NiIsImtpZCI6IjRKRER3RHNxNmgwRUV5STBDeXU4Y2ciLCJ0eXAiOiJhdCtqd3QifQ.eyJuYmYiOjE2NzA5OTM2OTMsImV4cCI6MTY3MTAxMTY5MywiaXNzIjoiaHR0cDovLzE5Mi4xNjguMC4xODo5MDkxIiwiYXVkIjoicXVhZHJpb25FcnBBUEkiLCJjbGllbnRfaWQiOiJxdWFkcmlvbi5jbGllbnQiLCJzdWIiOiJmYzBlYTU1Yy1jZDFhLTQ3N2UtYjlmYS0zN2E0YzA5M2M4ODIiLCJhdXRoX3RpbWUiOjE2NzA5OTM2OTMsImlkcCI6ImxvY2FsIiwibmFtZSI6IkF6aW0gTWFobXVkIiwiZW1haWwiOiJtYWhhbXVkLmF6aW1AZ21haWwuY29tIiwic2NvcGUiOlsib3BlbmlkIiwicHJvZmlsZSIsInF1YWRyaW9uRXJwQVBJIl0sImFtciI6WyJmb3JtcyJdfQ.quuCKunuxedPf5q6JW2Uz2nRh3QwISZd3PsZWWv-mLjQHLVg8oo9L0cpns0rAx_R3UKECcpmE7uXYgfBzKJx2h9o8zidDGIPKjlrGanrpl7mZhZqWlTcgk13W5LdeBAcxOreZXJv7lIKRkTD3CRlwSECRHFJWzf8-ODgEvbeXGcSM93RnjcTUOsjO8MsjvdLHZrow6stqymETFtKZQcTDaBeIhLbkg6Pjj3D_uue5Y_njLPF1LMgp-qMoaSBLJCFYIfhClMMqqeqbJBKtbd7b1PPV0tXMI91SONqszFKu4bpM5UBguzcg4X5C-eJHdGRPuWQoNinXPi1WvLWIec3oQ"

if ( accessToken ) {
    baseAxios.defaults.headers.common['Authorization'] = `bearer ${accessToken}`;
}
